//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKnetLutron.DataModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsFloorType
    {
        public int Id { get; set; }
        public int FloorId { get; set; }
        public string FloorName { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.DateTime DateOfModified { get; set; }
        public int UserID { get; set; }
        public int UserModified { get; set; }
    }
}
