//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKnetLutron.DataModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleDetail()
        {
            this.WeeklySchedules = new HashSet<WeeklySchedule>();
        }
    
        public int ScheduleDetailId { get; set; }
        public int ScheduleId { get; set; }
        public string ScheduleName { get; set; }
        public int DeviceId { get; set; }
        public int InstanceId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int UserID { get; set; }
        public int UserModified { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.DateTime DateOfModified { get; set; }
        public int PropertyArrayIndex { get; set; }
        public System.DateTime ScheduleStartDate { get; set; }
        public System.DateTime ScheduleEndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklySchedule> WeeklySchedules { get; set; }
    }
}
