//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACKnetLutron.DataModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklySchedule
    {
        public int WeeklyScheduleId { get; set; }
        public int ScheduleDetailId { get; set; }
        public int SelectedDayId { get; set; }
        public System.DateTime SelectedTime { get; set; }
        public double PresentValue { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int UserID { get; set; }
        public int UserModified { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.DateTime DateOfModified { get; set; }
    
        public virtual ScheduleDetail ScheduleDetail { get; set; }
    }
}
